services:
  ems-frontend:
    build:
      context: /home/ubuntu/frontend
      args:
        - VITE_API_URL
        - VITE_WORKSTOCK_URL
        - VITE_WORKSTOCK_API_URL
        - VITE_LOGO_URL
    container_name: ems-frontend
    restart: always
    ports:
      - "80:3000"
    env_file:
      - /home/ubuntu/frontend/.env
    networks:
      - frontend-network

  workstock-frontend:
    build:
      context: /home/ubuntu/workstock-pro/frontend
      args:
        - VITE_API_BASE_URL
        - VITE_EMS_URL
        - VITE_LOGO_URL
    container_name: workstock-frontend
    restart: always
    ports:
      - "3001:80"
    env_file:
      - /home/ubuntu/workstock-pro/frontend/.env
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge