services:
  ems-frontend:
    image: ghcr.io/divyasree11-04/ems-frontend:latest
    container_name: ems-frontend
    restart: always
    ports:
      - "80:3000"
    env_file:
      - ./frontend/.env
    networks:
      - frontend-network
  workstock-frontend:
    image: ghcr.io/divyasree11-04/workstock-frontend:latest
    container_name: workstock-frontend
    restart: always
    ports:
      - "3001:80"
    env_file:
      - ../WorkStock-Pro/frontend/.env
    networks:
      - frontend-network
networks:
  frontend-network:
