version: "3.9"
services:
  employee-service:
    build: .
    container_name: employee-service
    restart: always
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DATABASE_URL=postgres://ems_db:123@172.31.2.91:5432/ems_dbs1
      - JWT_SECRET=ems_2026
    networks:
      - ems-network

networks:
  ems-network:
    external: true
