version: "3.9"
services:
  attendance-service:
    build: .
    container_name: attendance-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://ems_db:123@172.31.2.91:5432/ems_dbs1
      - JWT_SECRET=ems_2026
    networks:
      - ems-network

networks:
  ems-network:
    external: true
