version: "3.9"
services:
  meeting-service:
    build: .
    container_name: meeting-service
    restart: always
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - DATABASE_URL=postgres://postgres:data7@172.31.14.42:5432/ems_dbs1
      - JWT_SECRET=ems_2026
    networks:
      - ems-network

networks:
  ems-network:
    external: true
