   name: production-build
   on:
     push:
       branches: [production]
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: docker/login-action@v3
           with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
         - uses: docker/build-push-action@v6
           with:
             context: ./backend
             push: true
             tags: |
               ${{ secrets.DOCKERHUB_USERNAME }}/ems-backend:production-${{ github.sha }}
               ${{ secrets.DOCKERHUB_USERNAME }}/ems-backend:production
         - uses: docker/build-push-action@v6
           with:
             context: ./frontend
             push: true
             tags: |
               ${{ secrets.DOCKERHUB_USERNAME }}/ems-frontend:production-${{ github.sha }}
               ${{ secrets.DOCKERHUB_USERNAME }}/ems-frontend:production
